export const AGREGAR_CARTA = "AGREGAR_CARTA";
export const AGREGAR_CARTA_EXITO = "AGREGAR-CARTA_EXITO";
export const AGREGAR_CARTA_ERROR = "AGREGAR-CARTA_ERROR";

export const COMENZAR_DESCARGA_CARTAS = "COMENZAR_DESCARGA_CARTAS";
export const DESCARGA_CARTAS_EXITO = "DESCARGA_CARTAS_EXITO";
export const DESCARGA_CARTAS_ERROR = "DESCARGA_CARTAS_ERROR";

export const OBTENER_CARTA_ELIMINAR = "OBTENER_CARTA_ELIMINAR";
export const CARTA_ELIMINADA_EXITO = "CARTA_ELIMINADA_EXITO";
export const CARTA_ELIMINADA_ERROR = "CARTA_ELIMINADA_ERROR";

export const OBTENER_CARTA_EDITAR = "OBTENER_CARTA_EDITAR";
export const COMENZAR_EDICION_CARTA = "COMENZAR_EDICION_CARTA";
export const CARTA_EDITADA_EXITO = "CARTA_EDITADA_EXITO";
export const CARTA_EDITADA_ERROR = "CARTA_EDITADA_ERROR";

export const MOSTRAR_ALERTA = "MOSTRAR_ALERTA";
export const OCULTAR_ALERTA = "OCULTAR_ALERTA";

export const BUSCAR_CARTA = "BUSCAR_CARTA";
export const CARTA_ENCONTRADA_EXITO = "CARTA_ENCONTRADA_EXITO";
export const CARTA_ENCONTRADA_ERROR = "CARTA_ENCONTRADA_ERROR";
